### ISSUE TITLE
can you do an unc0ver version of Taiwanese translation 

### ISSUE THREAD

**Issue by olivertzeng** [powenn/Taurine-powentest#3]
https://github.com/pwn20wndstuff/Undecimus

**Comment by powenn** [comment]
> https://github.com/pwn20wndstuff/Undecimus

unassociated issue

**Comment by olivertzeng** [comment]
https://github.com/Samgisaninja/unc0ver-localizations

**Comment by powenn** [comment]
Last update was two years ago ,they don't add localization support anymore

**Comment by olivertzeng** [comment]
ok lol
